# Turns a built web bundle into a C++ translation unit.
#
# Run in script mode with -DINPUT_DIR=<dist> -DOUTPUT=<file.cpp>. Every file
# becomes a byte array plus an entry in one table, so the server can answer from
# memory and the binary stays the single artefact to deploy.

if(NOT DEFINED INPUT_DIR OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "embed_web.cmake needs -DINPUT_DIR and -DOUTPUT")
endif()

file(GLOB_RECURSE WEB_FILES RELATIVE "${INPUT_DIR}" "${INPUT_DIR}/*")
list(SORT WEB_FILES)
if(NOT WEB_FILES)
  message(FATAL_ERROR "no files under ${INPUT_DIR}; build the frontend first")
endif()

set(BODY "// Generated by cmake/embed_web.cmake. Do not edit.\n")
string(APPEND BODY "#include \"http/web_assets.hpp\"\n\nnamespace nanotts {\nnamespace {\n\n")

set(TABLE "")
set(INDEX 0)
foreach(REL IN LISTS WEB_FILES)
  file(READ "${INPUT_DIR}/${REL}" HEX HEX)
  string(LENGTH "${HEX}" HEXLEN)
  math(EXPR NBYTES "${HEXLEN} / 2")
  string(REGEX REPLACE "(..)" "0x\\1," BYTES "${HEX}")
  # Wrap so no source line runs to a megabyte; some compilers dislike that.
  string(REGEX REPLACE "((0x..,){20})" "\\1\n" BYTES "${BYTES}")

  get_filename_component(EXT "${REL}" LAST_EXT)
  string(TOLOWER "${EXT}" EXT)
  set(MIME "application/octet-stream")
  if(EXT STREQUAL ".html")
    set(MIME "text/html; charset=utf-8")
  elseif(EXT STREQUAL ".js")
    set(MIME "text/javascript; charset=utf-8")
  elseif(EXT STREQUAL ".css")
    set(MIME "text/css; charset=utf-8")
  elseif(EXT STREQUAL ".json" OR EXT STREQUAL ".map")
    set(MIME "application/json")
  elseif(EXT STREQUAL ".svg")
    set(MIME "image/svg+xml")
  elseif(EXT STREQUAL ".png")
    set(MIME "image/png")
  elseif(EXT STREQUAL ".webp")
    set(MIME "image/webp")
  elseif(EXT STREQUAL ".ico")
    set(MIME "image/x-icon")
  elseif(EXT STREQUAL ".woff2")
    set(MIME "font/woff2")
  endif()

  string(APPEND BODY "const unsigned char kAsset${INDEX}[] = {\n${BYTES}\n};\n\n")
  string(APPEND TABLE
    "    {\"${REL}\", \"${MIME}\", {reinterpret_cast<const char*>(kAsset${INDEX}), ${NBYTES}}},\n")
  math(EXPR INDEX "${INDEX} + 1")
endforeach()

string(APPEND BODY "const WebAsset kAssets[] = {\n${TABLE}};\n\n}  // namespace\n\n")
string(APPEND BODY "std::span<const WebAsset> embedded_web() { return kAssets; }\n\n")
string(APPEND BODY "}  // namespace nanotts\n")

file(WRITE "${OUTPUT}" "${BODY}")
list(LENGTH WEB_FILES COUNT)
message(STATUS "embedded ${COUNT} web asset(s) into ${OUTPUT}")
